site_name: nomad-visu
site_url: https://nomad-coe.github.io/nomad-visu/
repo_name: nomad-coe/nomad-visu
repo_url: https://github.com/nomad-coe/nomad-visu

nav:
  - Home: 'index.md'
  - Getting started:
    - Setup: 'setup.md'
    - Introduction: 'introduction.md'
    - Examples: 'examples.md'
    # - octet: 'examples/octet_binaries.ipynb'
  - References: 'library.md'

theme:
  name: material
  features:
    - navigation.expand
  highlightjs: true
  hljs_style: github
  hljs_languages:
    - python
    - bash
  navigation_depth: 2

plugins:
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
  # - mkdocs-jupyter:
  #     execute: true
  #     kernel: nomad-visu
  - autorefs

watch:
  - src