site_name: nomad-visu
site_description: "A Python package for atomistic data visualisation"
site_url: https://nomad-coe.github.io/nomad-visu/
repo_name: nomad-coe/nomad-visu
repo_url: https://github.com/nomad-coe/nomad-visu

nav:
  - Home: "index.md"
  - "overview.md"
  - "examples.md"
  - "references.md"
  - "development.md"

theme:
  name: material
  features:
    - navigation.expand
    # - navigation.tabs
  highlightjs: true
  hljs_style: github
  hljs_languages:
    - python
    - bash
  navigation_depth: 2

plugins:
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src] # search packages in the src folder
          members_order: source
          show_source: false
  - autorefs

watch:
  - src
