[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "nomad_lab_visualizer"
description = "This is plot/visualizer widget for atomistic structures which can be used in Jupyter Notebooks."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    'jupyter',
    'ipywidgets',
    'plotly',
    'jupyter_jsmol',
    'numpy',
    'pandas',
    'scipy',
    'scikit-learn'
]
# keywords = ["one", "two"]
# license = {text = "BSD 3-Clause License"}
# dynamic = ["version"]

[project.optional-dependencies] 
test = ["pytest"]

# [project.scripts]
# my-script = "my_package.module:function"

# ... other project metadata fields as specified in:
#     https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
